export const allFilters = [
  {
    name: 'id',
    type: 'Integer',
    list: null,
    comment: 'The id of a resource',
    pattern: '[0-9]+',
  },
  {
    name: 'matchday',
    type: 'Integer',
    list: null,
    comment: '',
    pattern: '[1-4]+[0-9]*',
  },
  {
    name: 'season',
    type: 'String',
    list: null,
    comment: 'The starting year of a season e.g. 2017 or 2016',
    pattern: 'YYYY',
  },
  {
    name: 'status',
    type: 'Enum',
    list: [
      'SCHEDULED',
      'LIVE',
      'IN_PLAY',
      'PAUSED',
      'FINISHED',
      'POSTPONED',
      'SUSPENDED',
      'CANCELED',
    ],
    comment: 'The status of a match',
    pattern: '[A-Z]+',
  },
  {
    name: 'venue',
    type: 'Enum',
    list: ['HOME', 'AWAY'],
    comment: 'Defines the venue (type)',
    pattern: '[A-Z]+',
  },
  {
    name: 'dateFrom',
    type: 'String',
    list: null,
    comment: 'e.g. 2018-06-22',
    pattern: 'YYYY-MM-dd',
  },
  {
    name: 'dateTo',
    type: 'String',
    list: null,
    comment: 'e.g. 2018-06-22',
    pattern: 'YYYY-MM-dd',
  },
  {
    name: 'stage',
    type: 'String',
    list: null,
    comment:
      'Check the season node for available stages of a particular competition/season',
    pattern: '[A-Z]+',
  },
  {
    name: 'plan',
    type: 'Enum',
    list: ['TIER_ONE', 'TIER_TWO', 'TIER_THREE', 'TIER_FOUR'],
    comment: '',
    pattern: '[A-Z]+',
  },
  {
    name: 'competitions',
    type: 'String',
    list: null,
    comment: 'Comma separated list of competition ids.',
    pattern: 'd+,d+',
  },
  {
    name: 'group',
    type: 'String',
    list: null,
    comment: 'Allows filtering for groupings in a competition',
    pattern: '[A-Z]+',
  },
  {
    name: 'limit',
    type: 'Integer',
    list: null,
    comment: 'Limits your result set to the given number. Defaults to 10',
    pattern: 'd+',
  },
  {
    name: 'standingType',
    type: 'String',
    list: null,
    comment: 'TOTAL (default) | HOME | AWAY',
    pattern: '[A-Z]+',
  },
  {
    name: 'search',
    type: 'String',
    list: null,
    comment: '',
    pattern: '[0-9A-Z]+',
  },
]
